import math
from decimal import Decimal
from fractions import Fraction
import random
import copy

print('#ЧИСЛА', 'True' if True else 'False')
print('#ЧИСЛА', 'True' if False else 'False')
print('#ЧИСЛА', 'text')
print('#ЧИСЛА', 1, 2, 3, sep='***')
print('#ЧИСЛА', *[1,2,3], sep='\n')
print('#ЧИСЛА', (2+4)*2)
print('#ЧИСЛА', 2+4*2)
print('#ЧИСЛА', 2+4.0)
print('#ЧИСЛА', 0.1 + 0.1 + 0.1)
print('#ЧИСЛА', 0.1 + 0.1 + 0.1 - 0.3)
print('#ЧИСЛА', int(3.1415))
print('#ЧИСЛА', float(3))
print('#ЧИСЛА', 3**2)
print('#ЧИСЛА', 144 ** .5)
print('#ЧИСЛА', pow(144, .5))
print('#ЧИСЛА', math.sqrt(144))
print('#ЧИСЛА', 4/2+3)
print('#ЧИСЛА', 1/3.0)
print('#ЧИСЛА', 10/4)
print('#ЧИСЛА', 10//4)
print('#ЧИСЛА', 10//4.0)
print('#ЧИСЛА', 5//-2)
print('#ЧИСЛА', 25%6)
print('#ЧИСЛА', math.floor(2.5))
print('#ЧИСЛА', math.floor(-2.5))
print('#ЧИСЛА', math.trunc(2.5))
print('#ЧИСЛА', math.trunc(-2.5))
print('#ЧИСЛА', math.pi)
print('#ЧИСЛА', math.e)
print('#ЧИСЛА', abs (-42.0))
print('#ЧИСЛА', sum((1, 2, 3, 4)))
print('#ЧИСЛА', min(3, 1, 2, 4))
print('#ЧИСЛА', max(3, 1, 2, 4))
print('#ЧИСЛА', 2<4 and 4<6)
print('#ЧИСЛА', 2<4>6)
print('#ЧИСЛА', 1<2<3.0<4)
print('#ЧИСЛА', 1>2>3.0>4)
print('#ЧИСЛА', 1==2<3 (1==2 and 2<3))
print('#ЧИСЛА', 1.1+2.2 == 3.3)
print('#ЧИСЛА', int(1.1+2.2) == int(3.3))
print('#ЧИСЛА', 1j * 1J)
print('#ЧИСЛА', 2 + 1j * 3)
print('#ЧИСЛА', (2+1j)*3)
print('#ЧИСЛА', 0o1)
print('#ЧИСЛА', 0xFF)
print('#ЧИСЛА', 0b10000)
print('#ЧИСЛА', oct(64))
print('#ЧИСЛА', hex(64))
print('#ЧИСЛА', bin(64))
print('#ЧИСЛА', eval('64'))
print('#ЧИСЛА', 1 << 2)
print('#ЧИСЛА', 1 | 2)
print('#ЧИСЛА', 1 & 1)
print('#ЧИСЛА', '%e'%0.33333)
print('#ЧИСЛА', '%4.2f'%0.333333)
print('#ЧИСЛА', '{0:4.2f}'.format(0.333))
print('#ЧИСЛА', Decimal('0.1') + Decimal('0.1') + Decimal('0.1') - Decimal('0.3'))
print('#ЧИСЛА', Fraction (4, 6))
print('#ЧИСЛА', random.choice(['a', 'b', 'c']))


print('#МАССИВЫ', [1, 2].append(3))
print('#МАССИВЫ', [1, 2].extend([3, 4]))
print('#МАССИВЫ', [1, 2].insert(1,'a'))
print('#МАССИВЫ', [1, 2].index(2))
print('#МАССИВЫ', [1, 2].count(2))
print('#МАССИВЫ', sorted(['b','c','a']))
print('#МАССИВЫ', ['b','c','a'].reverse())
print('#МАССИВЫ', copy.copy(['b','c','a']))
print('#МАССИВЫ', [1,2].clear())
print('#МАССИВЫ', ['a','b'].pop(1))
print('#МАССИВЫ', [1,2].remove(1))
