print('-----------------')
print('#1', 'a\nb\tc')
print('#2', len('a\nb\tc'))
print('#3', '''Always look
 on the bright
side of life.''')
print('#4', 'Always look\n on the bright\nside of life.'
)
print('#5', '-'*10)
print('-----------------')
print('#1')
for elem in 'hacker': print(elem, end='\n')
print('#2', 'k' in 'hacker')
print('#3', 'z' in 'hacker')
print('#4', 'spam' in 'abcspamdef')
print('#5', 'spam'[0] , 'spam'[-2])
print('-----------------')
print('#1', 'spam'[1:3], 'spam'[1:], 'spam'[1])
print('#2', '123456789'[1:7:2])
print('#3', '123456789'[::2])
print('#4', '12345'[::-1])
print('#5', '12345'[::-2])
print('-----------------')
print('#1', '1234567'[5:1:-1])
print('#2', 'spam'[slice(1, 3)])
print('#3', 'spam'[slice(None, None, -1)])
print('#4', int("42"), str(42))
print('#5', int ('1101' , 2))
print('-----------------')
print('#1', repr(42))
print('#2', repr('spam'))
print('#3', ord('s'))
print('#4', chr(115))
print('#5', bin(13))
print('-----------------')
print('#1', 'banana'.count('a'))
print('#2', 'Hello, welcome'.find('welcome'))
print('#3', 'Mi casa, su casa.'.index('casa'))
print('#4', sorted('cba'))
print('#5', 'Ёёж'.replace('Ё', 'Е').replace('ё', 'е'))
print('-----------------')
print('#1', 'h'.capitalize())
print('#2', 'Hello My'.swapcase())
print('#3', 'Welcome to'.title())
print('#4', 'Hello my friends'.upper())
print('#5', 'Hello my FRIENDS'.lower())
print('-----------------')
print('#1', 'Hello, And'.casefold())
print('#2', 'banana'.center(20, 'O'))
print('#3', 'H\te\tl\tl\to'.expandtabs())
print('#4', 'For only {price:.2f} dollars!'.format(price = 49))
print('#5', '#'.join(['John', 'Peter', 'Vicky']))
print('-----------------')
print('#1', 'welcome to the jungle'.split())
print('#2', ' spacious '.strip())
print('#3', 'spacious '.rstrip())
print('#4', 'Hello, welcome to my world.'.startswith('Hello'))
print('#1', 'world.'.endswith('.'))
print('-----------------')
print('#1', )
print('#2', )
print('#3', '50'.zfill(10))
print('#4', )
print('#5', )
print('-----------------')
print('#1', )
print('#2', )
print('#3', )
print('#4', )
print('#5', )
